# Generated by Django 4.2.5 on 2023-09-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_post_alter_comment_user_and_more'),
        ('post', '0003_like'),
    ]

    operations = [
    ]
